// Mock data for SSBU fighters - will be replaced with GraphQL data later
export const mockFighters = [
  { id: '1', name: 'Banjo Kazooie', gamePosition: 1 },
  { id: '2', name: 'Bayonetta', gamePosition: 2 },
  { id: '3', name: 'Bowser', gamePosition: 3 },
  { id: '4', name: 'Bowser Jr', gamePosition: 4 },
  { id: '5', name: 'Byleth', gamePosition: 5 },
  { id: '6', name: 'Captain Falcon', gamePosition: 6 },
  { id: '7', name: 'Chrom', gamePosition: 7 },
  { id: '8', name: 'Cloud', gamePosition: 8 },
  { id: '9', name: 'Corrin', gamePosition: 9 },
  { id: '10', name: 'Daisy', gamePosition: 10 },
  { id: '11', name: 'Dark Pit', gamePosition: 11 },
  { id: '12', name: 'Dark Samus', gamePosition: 12 },
  { id: '13', name: 'Diddy Kong', gamePosition: 13 },
  { id: '14', name: 'Donkey Kong', gamePosition: 14 },
  { id: '15', name: 'Dr Mario', gamePosition: 15 },
  { id: '16', name: 'Duck Hunt', gamePosition: 16 },
  { id: '17', name: 'Falco', gamePosition: 17 },
  { id: '18', name: 'Fox', gamePosition: 18 },
  { id: '19', name: 'Ganondorf', gamePosition: 19 },
  { id: '20', name: 'Greninja', gamePosition: 20 },
  { id: '21', name: 'Hero', gamePosition: 21 },
  { id: '22', name: 'Ice Climbers', gamePosition: 22 },
  { id: '23', name: 'Ike', gamePosition: 23 },
  { id: '24', name: 'Incineroar', gamePosition: 24 },
  { id: '25', name: 'Inkling', gamePosition: 25 },
  { id: '26', name: 'Isabelle', gamePosition: 26 },
  { id: '27', name: 'Jigglypuff', gamePosition: 27 },
  { id: '28', name: 'Joker', gamePosition: 28 },
  { id: '29', name: 'Kazuya', gamePosition: 29 },
  { id: '30', name: 'Ken', gamePosition: 30 },
  { id: '31', name: 'King Dedede', gamePosition: 31 },
  { id: '32', name: 'King K Rool', gamePosition: 32 },
  { id: '33', name: 'Kirby', gamePosition: 33 },
  { id: '34', name: 'Link', gamePosition: 34 },
  { id: '35', name: 'Little Mac', gamePosition: 35 },
  { id: '36', name: 'Lucario', gamePosition: 36 },
  { id: '37', name: 'Lucas', gamePosition: 37 },
  { id: '38', name: 'Lucina', gamePosition: 38 },
  { id: '39', name: 'Luigi', gamePosition: 39 },
  { id: '40', name: 'Mario', gamePosition: 40 },
  { id: '41', name: 'Marth', gamePosition: 41 },
  { id: '42', name: 'Mega Man', gamePosition: 42 },
  { id: '43', name: 'Meta Knight', gamePosition: 43 },
  { id: '44', name: 'Mewtwo', gamePosition: 44 },
  { id: '45', name: 'Mii Fighters', gamePosition: 45 },
  { id: '46', name: 'Min Min', gamePosition: 46 },
  { id: '47', name: 'Mr Game Watch', gamePosition: 47 },
  { id: '48', name: 'Ness', gamePosition: 48 },
  { id: '49', name: 'Olimar', gamePosition: 49 },
  { id: '50', name: 'Pac Man', gamePosition: 50 },
  { id: '51', name: 'Palutena', gamePosition: 51 },
  { id: '52', name: 'Peach', gamePosition: 52 },
  { id: '53', name: 'Pichu', gamePosition: 53 },
  { id: '54', name: 'Pikachu', gamePosition: 54 },
  { id: '55', name: 'Piranha Plant', gamePosition: 55 },
  { id: '56', name: 'Pit', gamePosition: 56 },
  { id: '57', name: 'Pokemon Trainer', gamePosition: 57 },
  { id: '58', name: 'Pyra Mythra', gamePosition: 58 },
  { id: '59', name: 'R O B', gamePosition: 59 },
  { id: '60', name: 'Richter', gamePosition: 60 },
  { id: '61', name: 'Ridley', gamePosition: 61 },
  { id: '62', name: 'Robin', gamePosition: 62 },
  { id: '63', name: 'Rosalina Luma', gamePosition: 63 },
  { id: '64', name: 'Roy', gamePosition: 64 },
  { id: '65', name: 'Ryu', gamePosition: 65 },
  { id: '66', name: 'Samus', gamePosition: 66 },
  { id: '67', name: 'Sephiroth', gamePosition: 67 },
  { id: '68', name: 'Sheik', gamePosition: 68 },
  { id: '69', name: 'Shulk', gamePosition: 69 },
  { id: '70', name: 'Simon', gamePosition: 70 },
  { id: '71', name: 'Snake', gamePosition: 71 },
  { id: '72', name: 'Sonic', gamePosition: 72 },
  { id: '73', name: 'Sora', gamePosition: 73 },
  { id: '74', name: 'Steve', gamePosition: 74 },
  { id: '75', name: 'Terry', gamePosition: 75 },
  { id: '76', name: 'Toon Link', gamePosition: 76 },
  { id: '77', name: 'Villager', gamePosition: 77 },
  { id: '78', name: 'Wario', gamePosition: 78 },
  { id: '79', name: 'Wii Fit Trainer', gamePosition: 79 },
  { id: '80', name: 'Wolf', gamePosition: 80 },
  { id: '81', name: 'Yoshi', gamePosition: 81 },
  { id: '82', name: 'Young Link', gamePosition: 82 },
  { id: '83', name: 'Zelda', gamePosition: 83 },
  { id: '84', name: 'Zero Suit Samus', gamePosition: 84 },
];
